activebuddy/activebuddy/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy


import django.contrib.auth


urlpatterns = [
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('__debug__', include('debug_toolbar.urls')),
    path('auth/', include('users.urls')),
    path('settings/', include('user_settings.urls')),
]

activebuddy/pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='homepage'),
    path('ss/', views.PlaceholderView.as_view(), name='placeholder'),
]

activebuddy/user_settings/urls.py
from django.urls import path

from . import views

app_name = 'settings'

urlpatterns = [
    path('', views.SettingsListView.as_view(), name='settings'),
]

    # path(
    #     "email/change/",
    #     views.BaseEmailChangeView.as_view(),
    #     name="base_email_update",
    # ),
    # path(
    #     "email/change/done",
    #     views.EmailChangeDoneView.as_view(),
    #     name="email_change_done",
    # )

activebuddy/users/urls.py
from django.urls import path
from django.contrib.auth import views as inbuilt
from django.urls import reverse_lazy

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', inbuilt.LoginView.as_view(), name='login'),
    path('logout/', inbuilt.LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),

    path('pwd-recovery/',
        inbuilt.PasswordChangeView.as_view(success_url=reverse_lazy('users:password_change_done')), 
        name="password_change"),
    path(
        "pwd-recovery/done/",
        inbuilt.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    
    path(
        "new-pwd/", 
        inbuilt.PasswordResetView.as_view(success_url=reverse_lazy('users:password_email_sent')), 
        name="password_reset"),
    path(
        "new-pwd/email-sent/",
        inbuilt.PasswordResetDoneView.as_view(),
        name="password_email_sent",
    ),
    path(
        "new-pwd/<uidb64>/<token>/",
        inbuilt.PasswordResetConfirmView.as_view(success_url=reverse_lazy('users:password_reset_complete')),
        name="password_reset_confirm",
    ),
    path(
        "new-pwd/done/",
        inbuilt.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    )
]

activebuddy/user_settings/models.py
from django.db import models

# Create your models here.

activebuddy/users/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin


class CustomUserManager(BaseUserManager):
    def create_user(self, username, email=None, password=None, **extra_fields):
        if not username:
            raise ValueError('The username field must be set.')
        user = self.model(username=username, email=email, **extra_fields)
        if password is None:
            user.set_unusable_password()
        user.save()
        return user

    def create_superuser(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        
        return self.create_user(username, email, password, **extra_fields)

class MyUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(verbose_name='Логин', max_length=50, unique=True)
    email = models.EmailField(verbose_name='Электронная почта', unique=True)
    first_name = models.CharField(verbose_name='Имя', max_length=100, blank=True)
    last_name = models.CharField(verbose_name='Фамилия', max_length=150, blank=True)
    patronim = models.CharField(verbose_name='Отчество', max_length=150, blank=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
#TODO: remove 'blank=True' for 'on_pause' when implementing progress pause algorithm
    on_pause = models.BooleanField(verbose_name='Прогресс приостановлен', default=False, blank=True)
    backup_email = models.EmailField(verbose_name='Резервная электронная почта', unique=True, null=True, blank=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email', 'password']

    objects = CustomUserManager()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._meta.get_field('password').verbose_name = 'Пароль'

    def __str__(self):
        return self.username

activebuddy/users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from django import forms

MyUser = get_user_model()

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = MyUser
        fields = ("username", "email", "password1", "password2")

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if MyUser.objects.filter(email=email).exists():
            raise forms.ValidationError("This email is already in use.")
        return email

    def save(self, commit=True):
        user = super(CustomUserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

class CustomUserChangeForm(UserChangeForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = MyUser
        fields = ("username", "email")

activebuddy/pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

from users.utils import on_pause_redirect

def index(request):
    template_name = 'pages/homepage.html'
    return render(request, template_name)

class PlaceholderView(LoginRequiredMixin, TemplateView):
    template_name = 'pages/placeholder.html'

    @on_pause_redirect
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

activebuddy/user_settings/views.py
from django.views.generic import ListView
from django.shortcuts import redirect
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin

class SettingsListView(LoginRequiredMixin, ListView):
    model = get_user_model()
    template_name = 'pages/settings.html'

    def get_object(self):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['email'] = user.email
        context['on_pause'] = user.on_pause
        context['backup_email'] = user.backup_email
        return context

    def post(self, request, *args, **kwargs):
        user = self.get_object()

        email = request.POST.get('email', '')
        on_pause = request.POST.get('on_pause', False) == 'True'
        backup_email = request.POST.get('backup_email', '')

        user.email = email
        user.on_pause = on_pause
        user.backup_email = backup_email
        user.save()

        return redirect('settings:settings')

activebuddy/users/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView, UpdateView

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from .forms import CustomUserCreationForm
from .models import MyUser

class RegisterView(CreateView):
    template_name = 'registration/registration_form.html'
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('pages:homepage')

activebuddy/templates/base.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        {% include "includes/header.html" %}
        <main>
            <div>
                {% block content %}{% endblock %}
            </div>
        </main>
        {% include "includes/footer.html" %}
    </body>
</html>

activebuddy/templates/includes/footer.html
<footer>
    Placeholder footer
</footer>

activebuddy/templates/includes/header.html
<header>
    <nav>
        <div>
            This is header Placeholder
            <ul>
                <li><a href="{% url 'pages:homepage' %}">Главная</a></li>
                <li><a href="#diary">Дневник</a></li>
                <li><a href="#shop">Магазин</a></li>
                <li><a href="#tamagotchi">Тамагочи</a></li>
                <li><a href="#settings">Параметры</a></li>
            </ul>

            {% if user.is_authenticated %}
                <span>Пользователь: <b>{{ user.username }}</b></span>
                <li>
                    <a href="{% url 'users:password_change' %}">Изменить пароль</a>
                </li>
                <li>
                    <form action="{% url 'users:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Logout</button>
                    </form>
                </li>
                </div>
            {% else %}
                <span>
                    <a href="{% url 'users:login' %}">Войти</a>
                    <a href="{% url 'users:register' %}">Зарегистрироваться</a>
                </span>
            {% endif %}
    </nav>
</header>

activebuddy/templates/pages/homepage.html
{% extends "base.html" %}
{% block title %}
    Главная страница Homepage
{% endblock %}
{% block content %}
    HomePage.
    {% if user.is_authenticated %}
        <h2>Current user: {{ user.username }}</h2>
    {% else %}
        <h2> You aren't logged in.</h2>
    {% endif %}
{% endblock %}

activebuddy/templates/pages/placeholder.html
<h1>Success!</h1>

activebuddy/templates/pages/settings.html
{% extends "base.html" %}
{% block title %}
    Параметры
{% endblock %}
{% block content %}
    Учётная запись
    {% if user.is_authenticated %}
        <h2>Current user: {{ user.username }}</h2>
        <hr>
        <h2>General Settings</h2>
        <form method="POST">
            {% csrf_token %}
            <p>
                <label for="email">Email:</label>
                <input type="email" id="email" name="email" value="{{ email }}">
            </p>
            <p>
                <label for="on_pause">On Pause:</label>
                <input type="checkbox" id="on_pause" name="on_pause" {% if on_pause %}checked{% endif %} value="True">
            </p>
            <p>
                <label for="backup_email">Backup Email:</label>
                <input type="email" id="backup_email" name="backup_email" value="{{ backup_email }}">
            </p>
            <p>
                <input type="submit" value="Update">
            </p>
        </form>
    {% else %}
        <h2>You aren't logged in.</h2>
    {% endif %}
{% endblock %}